### ISSUE TITLE
Streaming API requires explicit reading of every value in an input

### ISSUE THREAD

**Issue by kgilmer** [cbeust/klaxon#115]
I have a usecase in which I need to pull a single ID out of a large array of elements in a JSON.  I thought that the Streaming API would be a good fit for this but after implementing I found there to be no way to simply say "skip until you get to field $.x.y.z" and that to prevent parse errors I had to explicitly parse each value.  For my usecase it was not feasible to do this.  Later I found that PathMatcher was a good fit.  It may be worth adding details of this requirement (explicitly parse each value) in the README, or perhaps I got it all wrong.  If it's the latter then perhaps a better example in which you ignore some fields in the input JSON doc would be helpful.

**Comment by kgilmer** [comment]
IMHO the streaming api's general utility is limited due to the restriction that the input must be completely modeled by the parser.  It's not a question of granularity, more of having the ability to say "I don't care about anything but XYX".  This would allow the streaming API be light for the cases in which I'm just trying to pull a single field out of a big array.  In the code snippet in the README, I would like to see instead of:

`else -> Assert.fail("Unexpected name: $readName")`

Something like:

`else -> reader.skipNext()` 

And that method would not require me to know anything more about the structure of the JSON.

I see your point about deserializing at the array element level, and I could have done that.  But, it seems wasteful to deserialize into POJO if you're just looking to extract a single field value.

Generally speaking I'm happy with PathMatcher.  And I would probably continue to stick with it for these use cases going forward, even if changes were made to the streaming API.  And I agree about your concern of overlap.  My reason for opening this issue was (perhaps just for me) a misunderstanding about the intended usecase for the streaming API.

**Comment by cbeust** [comment]
Agree with all your points.

Basically, you are talking about providing something similar to SAX but for JSON. Maybe an API that would notify you each time it encounters a pair of "name: value" as long as value is a primitive type. But it gets hairy quickly: you need to maintain a stack of passed names so you know where you are, and what do you do when that `value` itself is a complex JSON object? You are basically reinventing `PathMatcher` now.

Speaking of which, I started experimenting with an advanced version of it, where you can attach paths directly to fields:

    data class WithPath(
        val id: Int,
        @Json(path = "$.person.name")
        val name: String
    )

    fun fieldWithPath() {
        val result = Klaxon()
            .parse<WithPath>(StringReader("""{
                "id": 2,
                "person": {
                   "name": "John"
                }
            }"""))
        assertThat(result).isEqualTo(WithPath(2, "John"))
    }

It works well in simple cases but it gets tricky for corner cases. And since it's just syntactic convenience over what `PathMatcher` listeners give you, I didn't experiment too far.

**Comment by cbeust** [comment]
I think this is becoming a bit more subjective in terms of API and "kotlinicity" :)

Also, as you demonstrated yourself, it's pretty easy to adjust the API to your liking with extension functions, but feel free to join #klaxon on Slack and start a discussion about the API style, I'm happy to make modifications if there's some agreement about a better API...

**Comment by kgilmer** [comment]
Haha, yes true.  Thanks for humoring me on this journey through API ergonomics in Kotlin.

**Comment by cbeust** [comment]
Closing this for now.
